#!/bin/bash


#clean up previous job (just in case)
rm -f finished

which module &&  module load matlab

echo "starting main"


export MATLABPATH=$MATLABPATH:$SERVICE_DIR
time matlab -nodisplay -nosplash -r main

#check for output files
if [ -s dwi.bvecs ] && [ -s dwi.bvals ]; then
	echo 0 > finished
else
	echo "bvecs or bvals  missing"
	echo 1 > finished
	exit 1
fi

